# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            id: security_service
    encoders:
        AppBundle\Security\User\WebserviceUser: bcrypt
    access_control:
        - { path: ^/backend , roles: ROLE_ADMIN }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            provider: db_provider
            form_login:
                login_path: login_page
                check_path: login_page
                default_target_path: backend_dashboard_homepage
            logout:
                path: /logout
                target: /