AppBundle\Entity\ProductCategory:
    type: entity
    table: product_category
    id:
        idProductCategory:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_product_category
            generator:
                strategy: IDENTITY
    fields:
        category:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
